---
kind: pipeline
name: audit

platform:
  os: linux
  arch: amd64

steps:
- name: build information
  image: node:lts
  commands:
  - node --version
  - npm --version

- name: install
  image: node:lts
  commands:
  - npm install

- name: audit
  image: node:lts
  commands:
  - npm audit

---
kind: pipeline
name: lint

platform:
  os: linux
  arch: amd64

steps:
- name: build information
  image: node:lts
  commands:
  - node --version
  - npm --version

- name: install
  image: node:lts
  commands:
  - npm install

- name: lint
  image: node:lts
  commands:
  - npx tslint --project .

---
kind: pipeline
name: unit tests (node:14)

platform:
  os: linux
  arch: amd64

steps:
- name: build information
  image: node:14
  commands:
  - node --version
  - npm --version

- name: install
  image: node:14
  commands:
  - npm install

- name: unit tests
  image: node:14
  commands:
  - npm run test

---
kind: pipeline
name: unit tests (node:lts)

platform:
  os: linux
  arch: amd64

steps:
- name: build information
  image: node:lts
  commands:
  - node --version
  - npm --version

- name: install
  image: node:lts
  commands:
  - npm install

- name: unit tests
  image: node:lts
  commands:
  - npm run test

---
kind: pipeline
name: size and timing (node:lts)

platform:
  os: linux
  arch: amd64

steps:
- name: slow-deps
  image: node:lts
  commands:
  - npm install -g slow-deps
  - slow-deps

...
