---
{
   "kind": "pipeline",
   "name": "audit",
   "steps": [
      {
         "commands": [
            "node --version",
            "npm --version"
         ],
         "image": "node:lts",
         "name": "build information"
      },
      {
         "commands": [
            "npm install"
         ],
         "image": "node:lts",
         "name": "install"
      },
      {
         "commands": [
            "npm audit"
         ],
         "image": "node:lts",
         "name": "audit"
      }
   ]
}
---
{
   "kind": "pipeline",
   "name": "lint",
   "steps": [
      {
         "commands": [
            "node --version",
            "npm --version"
         ],
         "image": "node:lts",
         "name": "build information"
      },
      {
         "commands": [
            "npm install"
         ],
         "image": "node:lts",
         "name": "install"
      },
      {
         "commands": [
            "npm run lint"
         ],
         "image": "node:lts",
         "name": "lint"
      }
   ]
}
---
{
   "kind": "pipeline",
   "name": "unit tests (node:12)",
   "steps": [
      {
         "commands": [
            "node --version",
            "npm --version"
         ],
         "image": "node:12",
         "name": "build information"
      },
      {
         "commands": [
            "npm install"
         ],
         "image": "node:12",
         "name": "install"
      },
      {
         "commands": [
            "npm run test"
         ],
         "image": "node:12",
         "name": "unit tests"
      }
   ]
}
---
{
   "kind": "pipeline",
   "name": "unit tests (node:14)",
   "steps": [
      {
         "commands": [
            "node --version",
            "npm --version"
         ],
         "image": "node:14",
         "name": "build information"
      },
      {
         "commands": [
            "npm install"
         ],
         "image": "node:14",
         "name": "install"
      },
      {
         "commands": [
            "npm run test"
         ],
         "image": "node:14",
         "name": "unit tests"
      }
   ]
}
---
{
   "kind": "pipeline",
   "name": "unit tests (node:16)",
   "steps": [
      {
         "commands": [
            "node --version",
            "npm --version"
         ],
         "image": "node:16",
         "name": "build information"
      },
      {
         "commands": [
            "npm install"
         ],
         "image": "node:16",
         "name": "install"
      },
      {
         "commands": [
            "npm run test"
         ],
         "image": "node:16",
         "name": "unit tests"
      }
   ]
}
---
{
   "kind": "pipeline",
   "name": "size and timing (node:lts)",
   "steps": [
      {
         "commands": [
            "npm install -g slow-deps",
            "slow-deps"
         ],
         "image": "node:lts",
         "name": "slow-deps"
      }
   ]
}
